### ISSUE TITLE
Tests are conflicting each other

### ISSUE THREAD

**Issue by perolavsvendsen** [equinor/sumo-wrapper-python#124]
When running same test in several instances simultaneously, they are conflicting each other (using same test case on Sumo). Either run sequentially, randomize the test case names, or do something else clever.

E.g. a test is trying to upload to "testcase" while another test is deleting it

**Comment by roywilly** [comment]
This is already solved by creating a new uuid upon runtime, see example here: https://github.com/equinor/sumo-wrapper-python/blob/main/tests/test_sumo_thin_client.py#L205
